### ISSUE TITLE
Support for repo shorthand syntax

### ISSUE THREAD

**Issue by pdehaan** [jonschlinkert/normalize-pkg#13]
### Steps to reproduce
1. Create a package.json file and set the repository to a shorthand GitHub "owner/repo" syntax:
   
   ``` json
   {
       "repository": "pdehaan/hapi-examples",
       "name": "normalize-pkg-test",
       "version": "1.0.0"
   }
   ```
2. Run `$ normalize`
### Actual results

``` json
{
  "repository": {
    "type": "",
    "url": "pdehaan/hapi-examples"
  },
  "name": "normalize-pkg-test",
  "version": "1.0.0",
  /* snip... */
}
```

Not sure if the shorthand is valid when using the longer object form of `repository`, or if you want to default the type to "git" and use something like [robertkowalski/**github-url-from-username-repo**](https://github.com/robertkowalski/github-url-from-username-repo) to expand the URL to longer form URL.

**Comment by doowb** [comment]
This is normalizing the `repository` field to the short version now.
