### ISSUE TITLE
author fields not being parsed correctly

### ISSUE THREAD

**Issue by pdehaan** [jonschlinkert/normalize-pkg#5]
### Steps to reproduce:
1. `$ touch index.js` (optional)
2. `$ npm init` (finish wizard, this step probably is a bit inconsistent based on your current npm config setup.)
3. `$ normalize`
### Actual results:

```
  "author": {
    "name": "Peter deHaan <peter@deseloper.com> (http://nodeexamples.com/)",
    "url": ""
  },
```
### Expected results:

```
"author": {
  "name": "Peter deHaan",
  "url": "http://nodeexamples.com/",
  "email": "peter@deseloper.com"
},
...
```

**Comment by doowb** [comment]
The normalized author field is now the string version so it's not expanded into an object.
