### ISSUE TITLE
try to extract homepage url from repository

### ISSUE THREAD

**Issue by pdehaan** [jonschlinkert/normalize-pkg#8]
Similar to #7, but I think it'd be neat if normalize could detect that I don't have a `homepage` defined, then try and set a smart default if it can parse a GitHub URL from the repository (if it exists).

Relevant: https://github.com/visionmedia/node-github-url-from-git

Not sure how/if it should handle non-GitHub repo URIs since those may not always have a public HTTP site to point to.

**Comment by doowb** [comment]
The `homepage` field is normalized using existing repository data now.
